### ISSUE TITLE
more notes in chart but i cant hit them

### ISSUE THREAD

**Issue by PoketrainerMS** [koneko/4koneko#1]
tried playing a chart but it had a bunch of notes to the right that i couldnt hit and they're counting against me

[Screen recording 2023-04-04 10.59.16 AM.webm](https://user-images.githubusercontent.com/83524620/229834464-6bd864c5-f480-44f0-bb3b-edebec043b36.webm)
the end where i stop hitting anything is me hitting everything else trying to find what the keybinds are for the extra notes

**Comment by koneko** [comment]
Oh, thats an issue on my part. Its because I have not implemented support for 7k games, which is why its all like that. I'll quickly add a hotfix to prevent playing 7k games. Please stick to the 4 key ones.

**Comment by PoketrainerMS** [comment]
ok, thanks!
