### ISSUE TITLE
I can't change my hotkeys.

### ISSUE THREAD

**Issue by BruhMoment42211** [koneko/4koneko#2]
I try to change my hotkeys because I don't like using DFJK, but it's not working, I try to put another set of keys and I save, and go to a song, but my keys do not work, and it's always DFJK, Is this a bug... Can you guys help me?

**Comment by koneko** [comment]
can you please send me a screenshot of the settings page?

**Comment by BruhMoment42211** [comment]
Sure thing, but it just does not save the setting page is the same but i press save and try a map its always DF JK.

**Comment by BruhMoment42211** [comment]
![image](https://github.com/koneko/4koneko/assets/93952435/16b618fa-06c2-48be-93b8-cbfa0990307b)

**Comment by koneko** [comment]
Yep, its an issue on my end, a typo guard clause prevented the change from taking place, should be fixed from now on.
