### ISSUE TITLE
arrow/note spawn time is wrong

### ISSUE THREAD

**Issue by TripleDaylinq** [koneko/4koneko#3]
hey, I just wanna say that I really like open source stuff like this. Really helped me out with something I wanted to do.

But lets get serious for a moment:
I was looking through your code and I saw that you spawn the arrows at their stored timing point, but this is not correct. The timing point is the point at wich the note needs to be hit.
The point at wich the note should be spawned should be as follows instead:
'Stored timing point' minus 'time it takes for the note to go from the top of the screen into the receptor'

ive made a hacky fix for this, but you might want to make a more permanent solution if you care about it.
I changed the arrow speed to be the global speed everywhere (this makes the speed easier to track) and I added the following code to the updateArrows() if statement in script.js.
note.seconds - ((screenHeight * 0.8)/this.globalSpeed)*17 <= this.ms 

17 is deliberately chozen because updateArrows runs (almost) every 17ms and (screenHeight * 0.8) is where the receptors are according to the calculateY function

**Comment by koneko** [comment]
thank you for raising this issue and for your words of praise. you are however wrong, i already accounted for this when creating notes within the map.js, making this break instead of fix. i havent actually tested this code, but if memory serves right, thats how i made it.

**Comment by TripleDaylinq** [comment]
Yea, I did see that you tried to fix this by doing:
if (!params.get("disableGlobalOffset")) globalInitialStartTime = parsed["TimingPoints"][0]["StartTime"] || 0
and
let seconds = parseInt(note["StartTime"]) - parseInt(globalInitialStartTime)

but that starts the map waaaaay before it should actually start and doesnt take into account the time it takes for the note to get to the receptor at all.

If you play the song "Intro" on your page you can clearly feel that the timing is way off.
The first note should be at the first beat after the clap sound in the song, but it just comes emediately.

If you change the code to simply be
let seconds = parseInt(note["StartTime"])
then you will see that the notes spawn at the time at which they should be hit.
After then adding my fix as explained earlier, they spawn slightly earlier and end up in the receptor at the right time.

**Comment by koneko** [comment]
Really? seems that its a quaver map issue then or something, since on the
map "Chimera" my timings line up perfectly. i would have to investigate
this more and i dont want to do that, given that this is "finished". i am
however working on a c# recreation, with the intention to fix the bugs and
make it better. if you would like to, please make a pull request with your
fix and ill merge it.

**Comment by TripleDaylinq** [comment]
Sure, I will do that. I wasn't working in your git repo directly, so I'll have to recreate it real quick. Won't be long. You'll see it coming
